version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/game-library-frontend/app"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "cargo"
    directories:
      - "/game-library-frontend"
      - "/game-library-service"
      - "/user-management-service"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
