name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Update container
        run: sudo apt update

      - name: Install Rust nightly
        run: rustup override set nightly

      - name: Cache cargo
        uses:  Swatinem/rust-cache@v2
        id: cache-cargo

      - name: Cache npm
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install sqlx
        run: cargo install sqlx-cli --no-default-features --features sqlite

      - name: Install JavaScript dependencies
        run: |
          cd game-library-frontend/app
          npm install

      - name: Build GLF app
        run: |
          cd game-library-frontend/app
          npm run build

      - name: Test GLF app
        run: |
          cd game-library-frontend/app
          npm run test

      - name: Set up projects database
        run: |
          cd game-library-service
          DATABASE_URL=sqlite://projects.db sqlx database setup

      - name: Set up users database
        run: |
          cd user-management-service
          DATABASE_URL=sqlite://users.db sqlx database setup

      - name: Run tests
        run: cargo test
